apiVersion: apps/v1
kind: Deployment

metadata:
  name: dpy-simple-echo
  labels:
    app: simple-echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-echo
  template:
    metadata:
      labels:
        app: simple-echo
    spec:
      containers:
      - name: simple-echo
        image: owosso1212/hostname:latest
        ports:
        - containerPort: 80

